# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: md-editor CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Inject dependence
        uses: borales/actions-yarn@master
        with:
          cmd: install
      - name: Build
        uses: borales/actions-yarn@master
        with:
          cmd: ci
      - name: deploy
        uses: borales/actions-yarn@master
        with:
          cmd: gh-pages
